# Generated by Django 3.1.4 on 2020-12-12 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=10)),
                ('corrugated_cardboard', models.FloatField()),
                ('paper', models.FloatField()),
                ('glass', models.FloatField()),
                ('metal', models.FloatField()),
                ('plastic_1', models.FloatField()),
                ('plastic_2', models.FloatField()),
                ('plastic_3', models.FloatField()),
                ('plastic_4', models.FloatField()),
                ('plastic_5', models.FloatField()),
                ('plastic_6', models.FloatField()),
                ('plastic_7', models.FloatField()),
                ('plastic_other', models.FloatField()),
                ('trash', models.FloatField()),
                ('did_compost', models.BooleanField()),
                ('compost_reason', models.TextField()),
                ('did_reuse', models.BooleanField()),
                ('reuse_items', models.TextField()),
                ('learned_this_week', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_assessed_trash', models.BooleanField()),
                ('was_aware_of_municipality_program', models.BooleanField()),
                ('people_in_household', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
