# Generated by Django 3.1.6 on 2021-02-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pti', '0003_auto_20210206_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassessment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyassessment',
            name='compost_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyassessment',
            name='learned_this_week',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyassessment',
            name='reused_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
